/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author jackie-sally
 */
public class CourseMenu extends javax.swing.JFrame {
    
    DefaultTableModel dm;
    /**
     * Creates new form CourseMenu
     */
    public CourseMenu() {
        initComponents();
         
    }
    //Filter data
    private void filter(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dm);
        jTableMenu.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Sidepanel = new javax.swing.JPanel();
        jPanelView = new javax.swing.JPanel();
        jButtonViewCourse = new javax.swing.JButton();
        jPanelManage = new javax.swing.JPanel();
        jButtonCreateCourse = new javax.swing.JButton();
        jPanelHome = new javax.swing.JPanel();
        jHomeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMenu = new javax.swing.JTable();
        jTextFilter = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(250, 250, 250));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sidepanel.setBackground(new java.awt.Color(23, 35, 51));
        Sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelView.setBackground(new java.awt.Color(23, 35, 51));

        jButtonViewCourse.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jButtonViewCourse.setForeground(new java.awt.Color(255, 255, 255));
        jButtonViewCourse.setText("View Course");
        jButtonViewCourse.setBorder(null);
        jButtonViewCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonViewCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonViewCourseMouseExited(evt);
            }
        });
        jButtonViewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelViewLayout = new javax.swing.GroupLayout(jPanelView);
        jPanelView.setLayout(jPanelViewLayout);
        jPanelViewLayout.setHorizontalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelViewLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonViewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelViewLayout.setVerticalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonViewCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        Sidepanel.add(jPanelView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 220, 60));

        jPanelManage.setBackground(new java.awt.Color(23, 35, 51));

        jButtonCreateCourse.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jButtonCreateCourse.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCreateCourse.setText("Manage Course");
        jButtonCreateCourse.setBorder(null);
        jButtonCreateCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCreateCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCreateCourseMouseExited(evt);
            }
        });
        jButtonCreateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelManageLayout = new javax.swing.GroupLayout(jPanelManage);
        jPanelManage.setLayout(jPanelManageLayout);
        jPanelManageLayout.setHorizontalGroup(
            jPanelManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelManageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonCreateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelManageLayout.setVerticalGroup(
            jPanelManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonCreateCourse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        Sidepanel.add(jPanelManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 220, 60));

        jPanelHome.setBackground(new java.awt.Color(23, 35, 51));

        jHomeButton.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jHomeButton.setForeground(new java.awt.Color(255, 255, 255));
        jHomeButton.setText("Home");
        jHomeButton.setBorder(null);
        jHomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jHomeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jHomeButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addComponent(jHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Sidepanel.add(jPanelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 220, 60));

        Background.add(Sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 683));

        jTableMenu.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Code", "Course Name", "Credit"
            }
        ));
        jTableMenu.setRowHeight(25);
        jTableMenu.setSelectionBackground(new java.awt.Color(61, 97, 155));
        jScrollPane1.setViewportView(jTableMenu);

        Background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 644, 426));

        jTextFilter.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jTextFilter.setText("Search...");
        jTextFilter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextFilter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFilterMouseClicked(evt);
            }
        });
        jTextFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFilterActionPerformed(evt);
            }
        });
        jTextFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFilterKeyReleased(evt);
            }
        });
        Background.add(jTextFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 170, 200, 27));

        jPanel1.setBackground(new java.awt.Color(23, 35, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        Background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 780, 2));

        jLabel1.setFont(new java.awt.Font("Futura", 0, 30)); // NOI18N
        jLabel1.setText("Course Overview");
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setColor(JPanel p) {
        p.setBackground(new Color(41,57,80));
    }
    public void resetColor(JPanel p) {
        p.setBackground(new Color(23,35,51));
    }
    private void jButtonCreateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateCourseActionPerformed
        new CreateCourse().setVisible(true);  
    }//GEN-LAST:event_jButtonCreateCourseActionPerformed
    public static void AddRowToJTable(Object [] dataRow) {
        DefaultTableModel model = (DefaultTableModel)jTableMenu.getModel();
        model.addRow(dataRow);
    }
    private void jTextFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFilterKeyReleased
        String query = jTextFilter.getText().toLowerCase();
        filter(query);
    }//GEN-LAST:event_jTextFilterKeyReleased

    private void jButtonViewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewCourseActionPerformed
        new ViewCourse().setVisible(true);
    }//GEN-LAST:event_jButtonViewCourseActionPerformed

    private void jTextFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFilterActionPerformed

    private void jButtonViewCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonViewCourseMouseEntered
        setColor(jPanelView);
    }//GEN-LAST:event_jButtonViewCourseMouseEntered

    private void jButtonViewCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonViewCourseMouseExited
        resetColor(jPanelView);
    }//GEN-LAST:event_jButtonViewCourseMouseExited

    private void jButtonCreateCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreateCourseMouseEntered
        setColor(jPanelManage);
    }//GEN-LAST:event_jButtonCreateCourseMouseEntered

    private void jButtonCreateCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreateCourseMouseExited
        resetColor(jPanelManage);
    }//GEN-LAST:event_jButtonCreateCourseMouseExited

    private void jHomeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHomeButtonMouseEntered
        setColor(jPanelHome);
    }//GEN-LAST:event_jHomeButtonMouseEntered

    private void jHomeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHomeButtonMouseExited
        resetColor(jPanelHome);
    }//GEN-LAST:event_jHomeButtonMouseExited

    private void jTextFilterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFilterMouseClicked
        jTextFilter.setText("");
    }//GEN-LAST:event_jTextFilterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseMenu().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Sidepanel;
    private javax.swing.JButton jButtonCreateCourse;
    private javax.swing.JButton jButtonViewCourse;
    private javax.swing.JButton jHomeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelManage;
    private javax.swing.JPanel jPanelView;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTableMenu;
    private javax.swing.JTextField jTextFilter;
    // End of variables declaration//GEN-END:variables
}
