/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author jackie-sally
 */
public class CourseMenu extends javax.swing.JFrame {
    
    DefaultTableModel dm;
    /**
     * Creates new form CourseMenu
     */
    public CourseMenu() {
        initComponents();
         
    }
    //Filter data
    private void filter(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dm);
        jTableMenu.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Sidepanel = new javax.swing.JPanel();
        jPanelViewResults = new javax.swing.JPanel();
        jButtonViewResults = new javax.swing.JButton();
        jPanelManageCourse = new javax.swing.JPanel();
        jButtonManageCourse = new javax.swing.JButton();
        jPanelHome = new javax.swing.JPanel();
        jHomeButton = new javax.swing.JButton();
        jPanelViewExams = new javax.swing.JPanel();
        jButtonViewExams = new javax.swing.JButton();
        jCourseBackgroundPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMenu = new javax.swing.JTable();
        jCourseLabel = new javax.swing.JLabel();
        jCourseSearchFilter = new javax.swing.JTextField();
        jCourseComboBox2 = new javax.swing.JComboBox<>();
        jBlueLinePanelC = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(930, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(250, 250, 250));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sidepanel.setBackground(new java.awt.Color(23, 35, 51));
        Sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelViewResults.setBackground(new java.awt.Color(23, 35, 51));

        jButtonViewResults.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jButtonViewResults.setForeground(new java.awt.Color(255, 255, 255));
        jButtonViewResults.setText("View Results");
        jButtonViewResults.setBorder(null);
        jButtonViewResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonViewResultsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonViewResultsMouseExited(evt);
            }
        });
        jButtonViewResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewResultsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelViewResultsLayout = new javax.swing.GroupLayout(jPanelViewResults);
        jPanelViewResults.setLayout(jPanelViewResultsLayout);
        jPanelViewResultsLayout.setHorizontalGroup(
            jPanelViewResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonViewResults, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanelViewResultsLayout.setVerticalGroup(
            jPanelViewResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelViewResultsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonViewResults, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Sidepanel.add(jPanelViewResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 190, 60));

        jPanelManageCourse.setBackground(new java.awt.Color(23, 35, 51));

        jButtonManageCourse.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jButtonManageCourse.setForeground(new java.awt.Color(255, 255, 255));
        jButtonManageCourse.setText("Manage Course");
        jButtonManageCourse.setBorder(null);
        jButtonManageCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonManageCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonManageCourseMouseExited(evt);
            }
        });
        jButtonManageCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelManageCourseLayout = new javax.swing.GroupLayout(jPanelManageCourse);
        jPanelManageCourse.setLayout(jPanelManageCourseLayout);
        jPanelManageCourseLayout.setHorizontalGroup(
            jPanelManageCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonManageCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanelManageCourseLayout.setVerticalGroup(
            jPanelManageCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonManageCourse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        Sidepanel.add(jPanelManageCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 190, 60));

        jPanelHome.setBackground(new java.awt.Color(23, 35, 51));
        jPanelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jHomeButton.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jHomeButton.setForeground(new java.awt.Color(255, 255, 255));
        jHomeButton.setText("Home");
        jHomeButton.setBorder(null);
        jHomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jHomeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jHomeButtonMouseExited(evt);
            }
        });
        jPanelHome.add(jHomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 60));

        Sidepanel.add(jPanelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 190, 60));

        jPanelViewExams.setBackground(new java.awt.Color(23, 35, 51));

        jButtonViewExams.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jButtonViewExams.setForeground(new java.awt.Color(255, 255, 255));
        jButtonViewExams.setText("View Exams");
        jButtonViewExams.setBorder(null);
        jButtonViewExams.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonViewExamsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonViewExamsMouseExited(evt);
            }
        });
        jButtonViewExams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewExamsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelViewExamsLayout = new javax.swing.GroupLayout(jPanelViewExams);
        jPanelViewExams.setLayout(jPanelViewExamsLayout);
        jPanelViewExamsLayout.setHorizontalGroup(
            jPanelViewExamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonViewExams, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanelViewExamsLayout.setVerticalGroup(
            jPanelViewExamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonViewExams, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        Sidepanel.add(jPanelViewExams, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 190, 60));

        Background.add(Sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 680));

        jCourseBackgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        jCourseBackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableMenu.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Code", "Course Name", "Credit"
            }
        ));
        jTableMenu.setRowHeight(25);
        jTableMenu.setSelectionBackground(new java.awt.Color(61, 97, 155));
        jScrollPane1.setViewportView(jTableMenu);

        jCourseBackgroundPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 620, 440));

        jCourseLabel.setFont(new java.awt.Font("Futura", 0, 30)); // NOI18N
        jCourseLabel.setText("Course Overview ");
        jCourseBackgroundPanel.add(jCourseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jCourseSearchFilter.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jCourseSearchFilter.setText("Search...");
        jCourseSearchFilter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jCourseSearchFilter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCourseSearchFilterMouseClicked(evt);
            }
        });
        jCourseSearchFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCourseSearchFilterActionPerformed(evt);
            }
        });
        jCourseSearchFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCourseSearchFilterKeyReleased(evt);
            }
        });
        jCourseBackgroundPanel.add(jCourseSearchFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 150, 27));

        jCourseComboBox2.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jCourseComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select course", "Item 2", "Item 3", "Item 4" }));
        jCourseBackgroundPanel.add(jCourseComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 170, 27));

        jBlueLinePanelC.setBackground(new java.awt.Color(23, 35, 51));

        javax.swing.GroupLayout jBlueLinePanelCLayout = new javax.swing.GroupLayout(jBlueLinePanelC);
        jBlueLinePanelC.setLayout(jBlueLinePanelCLayout);
        jBlueLinePanelCLayout.setHorizontalGroup(
            jBlueLinePanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        jBlueLinePanelCLayout.setVerticalGroup(
            jBlueLinePanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jCourseBackgroundPanel.add(jBlueLinePanelC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 740, 3));

        Background.add(jCourseBackgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 740, 680));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setColor(JPanel p) {
        p.setBackground(new Color(41,57,80));
    }
    public void resetColor(JPanel p) {
        p.setBackground(new Color(23,35,51));
    }
    private void jButtonManageCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageCourseActionPerformed
        new CreateCourse().setVisible(true);  
    }//GEN-LAST:event_jButtonManageCourseActionPerformed
    public static void AddRowToJTable(Object [] dataRow) {
        DefaultTableModel model = (DefaultTableModel)jTableMenu.getModel();
        model.addRow(dataRow);
    } 
    private void jButtonViewResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewResultsActionPerformed
        new ViewResults().setVisible(true);
    }//GEN-LAST:event_jButtonViewResultsActionPerformed

    private void jButtonViewResultsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonViewResultsMouseEntered
        setColor(jPanelViewResults);
    }//GEN-LAST:event_jButtonViewResultsMouseEntered

    private void jButtonViewResultsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonViewResultsMouseExited
        resetColor(jPanelViewResults);
    }//GEN-LAST:event_jButtonViewResultsMouseExited

    private void jButtonManageCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonManageCourseMouseEntered
        setColor(jPanelManageCourse);
    }//GEN-LAST:event_jButtonManageCourseMouseEntered

    private void jButtonManageCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonManageCourseMouseExited
        resetColor(jPanelManageCourse);
    }//GEN-LAST:event_jButtonManageCourseMouseExited

    private void jHomeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHomeButtonMouseEntered
        setColor(jPanelHome);
    }//GEN-LAST:event_jHomeButtonMouseEntered

    private void jHomeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHomeButtonMouseExited
        resetColor(jPanelHome);
    }//GEN-LAST:event_jHomeButtonMouseExited

    private void jCourseSearchFilterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCourseSearchFilterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jCourseSearchFilterMouseClicked

    private void jCourseSearchFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCourseSearchFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCourseSearchFilterActionPerformed

    private void jCourseSearchFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCourseSearchFilterKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jCourseSearchFilterKeyReleased

    private void jButtonViewExamsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonViewExamsMouseEntered
        setColor(jPanelViewExams);
    }//GEN-LAST:event_jButtonViewExamsMouseEntered

    private void jButtonViewExamsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonViewExamsMouseExited
        resetColor(jPanelViewExams);
    }//GEN-LAST:event_jButtonViewExamsMouseExited

    private void jButtonViewExamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewExamsActionPerformed
        new ViewExams().setVisible(true);
    }//GEN-LAST:event_jButtonViewExamsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseMenu().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Sidepanel;
    private javax.swing.JPanel jBlueLinePanelC;
    private javax.swing.JButton jButtonManageCourse;
    private javax.swing.JButton jButtonViewExams;
    private javax.swing.JButton jButtonViewResults;
    private javax.swing.JPanel jCourseBackgroundPanel;
    private javax.swing.JComboBox<String> jCourseComboBox2;
    private javax.swing.JLabel jCourseLabel;
    private javax.swing.JTextField jCourseSearchFilter;
    private javax.swing.JButton jHomeButton;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelManageCourse;
    private javax.swing.JPanel jPanelViewExams;
    private javax.swing.JPanel jPanelViewResults;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTableMenu;
    // End of variables declaration//GEN-END:variables
}
