/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
/**
 *
 * @author jackie-sally
 */
public class CreateExam extends javax.swing.JFrame {
    
    /**
     * Creates new form CreateExam
     */
    public CreateExam() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jHeaderLabel = new javax.swing.JLabel();
        jSelectCourseLabel = new javax.swing.JLabel();
        jCourseComboBox = new javax.swing.JComboBox<>();
        jDateLabel = new javax.swing.JLabel();
        jSelectTimeLabel = new javax.swing.JLabel();
        jLocationLabel = new javax.swing.JLabel();
        jAddCourseButton = new javax.swing.JButton();
        jTimeComboBox = new javax.swing.JComboBox<>();
        jDateDay = new javax.swing.JTextField();
        jTextLocation = new javax.swing.JTextField();
        jExamIDLabel = new javax.swing.JLabel();
        jExamID = new javax.swing.JTextField();
        jGenerateID = new javax.swing.JButton();
        jDateMonth = new javax.swing.JTextField();
        jDateYear = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jResetButton = new javax.swing.JButton();
        jCancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jExamTable = new javax.swing.JTable();
        jUpdateButton = new javax.swing.JButton();
        jDeleteButton = new javax.swing.JButton();
        jSearchField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        jHeaderLabel.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jHeaderLabel.setText("Manage exams");

        jSelectCourseLabel.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jSelectCourseLabel.setText("Select course:");

        jCourseComboBox.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "Item 1", "Item 2", "Item 3", "Item 4" }));

        jDateLabel.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jDateLabel.setText("Date:");

        jSelectTimeLabel.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jSelectTimeLabel.setText("Select time:");

        jLocationLabel.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLocationLabel.setText("Location:");

        jAddCourseButton.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jAddCourseButton.setText("Add course");
        jAddCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddCourseButtonActionPerformed(evt);
            }
        });

        jTimeComboBox.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jTimeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00" }));

        jDateDay.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jDateDay.setText("dd");
        jDateDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateDayMouseClicked(evt);
            }
        });
        jDateDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateDayActionPerformed(evt);
            }
        });

        jTextLocation.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jTextLocation.setText("Room A123");
        jTextLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextLocationMouseClicked(evt);
            }
        });

        jExamIDLabel.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jExamIDLabel.setText("Exam ID:");

        jExamID.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N

        jGenerateID.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jGenerateID.setText("Generate");
        jGenerateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenerateIDActionPerformed(evt);
            }
        });

        jDateMonth.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jDateMonth.setText("mm");
        jDateMonth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateMonthMouseClicked(evt);
            }
        });
        jDateMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateMonthActionPerformed(evt);
            }
        });

        jDateYear.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jDateYear.setText("yyyy");
        jDateYear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateYearMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel1.setText("/");

        jLabel2.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel2.setText("/");

        jResetButton.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jResetButton.setText("Reset");
        jResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetButtonActionPerformed(evt);
            }
        });

        jCancelButton.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jCancelButton.setText("Cancel");
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        jExamTable.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jExamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exam ID", "Date", "Time", "Location"
            }
        ));
        jScrollPane1.setViewportView(jExamTable);

        jUpdateButton.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jUpdateButton.setText("Save update");

        jDeleteButton.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jDeleteButton.setText("Delete");

        jSearchField.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jSearchField.setText("Search...");
        jSearchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSearchFieldMouseClicked(evt);
            }
        });
        jSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSelectCourseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jSelectTimeLabel)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jExamIDLabel)
                                        .addComponent(jLocationLabel)))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jExamID, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jGenerateID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jDateDay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDateYear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextLocation)
                                    .addComponent(jTimeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCourseComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jAddCourseButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jUpdateButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jHeaderLabel)
                .addGap(407, 407, 407))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSelectCourseLabel)
                            .addComponent(jCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDateLabel)
                            .addComponent(jDateDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jDateYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSelectTimeLabel)
                            .addComponent(jTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLocationLabel)
                            .addComponent(jTextLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jExamIDLabel)
                            .addComponent(jExamID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jGenerateID))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAddCourseButton)
                            .addComponent(jDeleteButton)
                            .addComponent(jUpdateButton))
                        .addGap(27, 27, 27)
                        .addComponent(jResetButton)
                        .addGap(28, 28, 28)
                        .addComponent(jCancelButton)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddCourseButtonActionPerformed

        //Check if course is selected
        if (jCourseComboBox.getSelectedItem() == "Make a Selection") {
            JOptionPane.showMessageDialog(null, "Course not selected!\nPlease select a course."); 
        } else {
            course = jCourseComboBox.getSelectedItem().toString();
        }
       
        //Check day
        if(jDateDay.getText().equalsIgnoreCase("dd") || jDateDay.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Day field is empty!\nPlease enter a day."); 
        }
        else {
            try { 
                int dd = Integer.parseInt(jDateDay.getText()); 
                if(dd <= 0 || dd >= 31) {
                    JOptionPane.showMessageDialog(null, "Invalid day!\nPlease enter a valid day."); 
                }
                else {
                    dateDay = dd;
                }  
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Day is not a valid number!\nPlease enter a valid day.");
            }
        }
        
        //Check month 
        if(jDateMonth.getText().equalsIgnoreCase("mm") || jDateMonth.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Month field is empty!\nPlease enter a month."); 
        }
        else {
            try { 
                int mm = Integer.parseInt(jDateMonth.getText()); 
                if(mm <= 0 || mm > 12) {
                    JOptionPane.showMessageDialog(null, "Invalid month!\nPlease enter a valid month."); 
                }
                else {
                    dateMonth = mm; 
                }  
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Month is not a valid number!\nPlease enter a valid month.");
            }
        }
        
        //Check year
        if(jDateYear.getText().equalsIgnoreCase("yyyy") || jDateYear.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Year field is empty!\nPlease enter a year."); 
        }
        else {
            try { 
                int yyyy = Integer.parseInt(jDateYear.getText()); 
                if(yyyy < 2020 || yyyy > 2025) {
                    JOptionPane.showMessageDialog(null, "Invalid year!\nPlease enter a valid year."); 
                }
                else {
                    dateYear = yyyy; 
                }  
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Year is not a valid number!\nPlease enter valid year.");
            }
        }
        
        //Check if time is selected 
        if (jTimeComboBox.getSelectedItem() == "Make a Selection") {
            JOptionPane.showMessageDialog(null, "Time not selected!\nPlease select a time."); 
        } else {
            time = jTimeComboBox.getSelectedItem().toString();
        }
        
        //Check if examID has been generated 
        if(jExamID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Exam ID has not been generated!\nPlease generate exam ID."); 
        }
        else {
            examID = jExamID.getText();
        }
        
    }//GEN-LAST:event_jAddCourseButtonActionPerformed

    private void jGenerateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenerateIDActionPerformed
       java.util.Random r = new java.util.Random();
        int start = 10000; 
        int end = 99999; 
        int result = r.nextInt(end-start) + start; 
        String id = "E" + String.valueOf(result);
        jExamID.setText(id); 
    }//GEN-LAST:event_jGenerateIDActionPerformed

    private void jDateDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateDayActionPerformed

    private void jDateDayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateDayMouseClicked
        jDateDay.setText("");
    }//GEN-LAST:event_jDateDayMouseClicked

    private void jDateMonthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateMonthMouseClicked
        jDateMonth.setText("");
    }//GEN-LAST:event_jDateMonthMouseClicked

    private void jDateYearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateYearMouseClicked
        jDateYear.setText("");
    }//GEN-LAST:event_jDateYearMouseClicked

    private void jTextLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextLocationMouseClicked
        jTextLocation.setText("");
    }//GEN-LAST:event_jTextLocationMouseClicked

    private void jResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetButtonActionPerformed
        jDateDay.setText("dd");
        jDateMonth.setText("mm");
        jDateYear.setText("yyyy");
        jTextLocation.setText("Room A123");
        jExamID.setText("");
        jTimeComboBox.setSelectedItem("Make a Selection");
        jCourseComboBox.setSelectedItem("Make a Selection");
        
    }//GEN-LAST:event_jResetButtonActionPerformed

    private void jDateMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateMonthActionPerformed
       
    }//GEN-LAST:event_jDateMonthActionPerformed

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jCancelButtonActionPerformed

    private void jSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchFieldActionPerformed

    private void jSearchFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchFieldMouseClicked
        jSearchField.setText("");
    }//GEN-LAST:event_jSearchFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateExam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddCourseButton;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JComboBox<String> jCourseComboBox;
    private javax.swing.JTextField jDateDay;
    private javax.swing.JLabel jDateLabel;
    private javax.swing.JTextField jDateMonth;
    private javax.swing.JTextField jDateYear;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JTextField jExamID;
    private javax.swing.JLabel jExamIDLabel;
    private javax.swing.JTable jExamTable;
    private javax.swing.JButton jGenerateID;
    private javax.swing.JLabel jHeaderLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLocationLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jResetButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSearchField;
    private javax.swing.JLabel jSelectCourseLabel;
    private javax.swing.JLabel jSelectTimeLabel;
    private javax.swing.JTextField jTextLocation;
    private javax.swing.JComboBox<String> jTimeComboBox;
    private javax.swing.JButton jUpdateButton;
    // End of variables declaration//GEN-END:variables
    private String course;
    private int dateDay;
    private int dateMonth;
    private int dateYear; 
    private String time; 
    private String location; 
    private String examID;
}
