/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.WrittenExam;
import java.util.*;
/**
 *
 * @author jackie-sally
 */
public class CreateExam extends javax.swing.JFrame {
    
    ArrayList<WrittenExam> exams; 
   
    /**
     * Creates new form CreateExam
     */
    public CreateExam() {
        initComponents();
        exams = new ArrayList<WrittenExam>(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jHeaderLabel = new javax.swing.JLabel();
        jSelectCourseLabel = new javax.swing.JLabel();
        jCourseComboBox = new javax.swing.JComboBox<>();
        jDateLabel = new javax.swing.JLabel();
        jSelectTimeLabel = new javax.swing.JLabel();
        jLocationLabel = new javax.swing.JLabel();
        jCreateExamButton = new javax.swing.JButton();
        jTimeComboBox = new javax.swing.JComboBox<>();
        jDateDay = new javax.swing.JTextField();
        jTextLocation = new javax.swing.JTextField();
        jExamIDLabel = new javax.swing.JLabel();
        jExamID = new javax.swing.JTextField();
        jGenerateID = new javax.swing.JButton();
        jDateMonth = new javax.swing.JTextField();
        jDateYear = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jResetButton = new javax.swing.JButton();
        jCancelButton = new javax.swing.JButton();
        jUpdateButton = new javax.swing.JButton();
        jDeleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        jHeaderLabel.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jHeaderLabel.setText("Manage exams");

        jSelectCourseLabel.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jSelectCourseLabel.setText("Select course:");

        jCourseComboBox.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCourseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCourseComboBoxActionPerformed(evt);
            }
        });

        jDateLabel.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jDateLabel.setText("Date:");

        jSelectTimeLabel.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jSelectTimeLabel.setText("Select time:");

        jLocationLabel.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLocationLabel.setText("Location:");

        jCreateExamButton.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jCreateExamButton.setText("Create exam");
        jCreateExamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateExamButtonActionPerformed(evt);
            }
        });

        jTimeComboBox.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jTimeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00" }));

        jDateDay.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jDateDay.setText("dd");
        jDateDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateDayMouseClicked(evt);
            }
        });
        jDateDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateDayActionPerformed(evt);
            }
        });

        jTextLocation.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jTextLocation.setText("Room A123");
        jTextLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextLocationMouseClicked(evt);
            }
        });

        jExamIDLabel.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jExamIDLabel.setText("Exam ID:");

        jExamID.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N

        jGenerateID.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jGenerateID.setText("Generate");
        jGenerateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenerateIDActionPerformed(evt);
            }
        });

        jDateMonth.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jDateMonth.setText("mm");
        jDateMonth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateMonthMouseClicked(evt);
            }
        });
        jDateMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateMonthActionPerformed(evt);
            }
        });

        jDateYear.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jDateYear.setText("yyyy");
        jDateYear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateYearMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel1.setText("/");

        jLabel2.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel2.setText("/");

        jResetButton.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jResetButton.setText("Reset");
        jResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetButtonActionPerformed(evt);
            }
        });

        jCancelButton.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jCancelButton.setText("Cancel");
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        jUpdateButton.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jUpdateButton.setText("Save update");

        jDeleteButton.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jDeleteButton.setText("Delete");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSelectCourseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSelectTimeLabel)
                            .addComponent(jLocationLabel)
                            .addComponent(jExamIDLabel))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextLocation)
                            .addComponent(jTimeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCourseComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDateDay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1)
                                .addGap(5, 5, 5)
                                .addComponent(jDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel2)
                                .addGap(8, 8, 8)
                                .addComponent(jDateYear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jExamID, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jGenerateID))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCreateExamButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jHeaderLabel)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jUpdateButton)))))))
                .addGap(39, 39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSelectCourseLabel)
                    .addComponent(jCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDateLabel)
                    .addComponent(jDateDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSelectTimeLabel)
                    .addComponent(jTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLocationLabel)
                    .addComponent(jTextLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jExamIDLabel)
                    .addComponent(jExamID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGenerateID))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCreateExamButton)
                    .addComponent(jDeleteButton)
                    .addComponent(jUpdateButton))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCancelButton)
                    .addComponent(jResetButton))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCreateExamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateExamButtonActionPerformed
        final int NUM_FIELDS = 7;
        int numCorrectFields = 0;
        boolean valid = true;
            
        //Get selected time from course combobox
        String selectedTime = jTimeComboBox.getSelectedItem().toString();
        int dd = Integer.parseInt(jDateDay.getText()); 
        int mm = Integer.parseInt(jDateMonth.getText()); 
        int yyyy = Integer.parseInt(jDateYear.getText()); 
        String date = yyyy + "-" + mm + "-" + dd;
        
        //Check if course is selected
        if (jCourseComboBox.getSelectedItem() == "Make a Selection") {
            JOptionPane.showMessageDialog(null, "Course not selected!\nPlease select a course."); 
        } else {
            course = jCourseComboBox.getSelectedItem().toString();
            numCorrectFields++;
         }
       
        //Check day
        if(jDateDay.getText().equalsIgnoreCase("dd") || jDateDay.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Day field is empty!\nPlease enter a day."); 
        } else {
             try {  
                   if(dd <= 0 || dd >= 31) {
                       JOptionPane.showMessageDialog(null, "Invalid day!\nPlease enter a valid day."); 
                  }
                  else {
                      dateDay = dd;
                      numCorrectFields++;
                  }  
              } catch (NumberFormatException e) {
                  JOptionPane.showMessageDialog(null, "Day is not a valid number!\nPlease enter a valid day.");
              }
         }
         //Check month 
         if(jDateMonth.getText().equalsIgnoreCase("mm") || jDateMonth.getText().isEmpty()) {
             JOptionPane.showMessageDialog(null, "Month field is empty!\nPlease enter a month."); 
          }
          else {
             try { 
                  if(mm <= 0 || mm > 12) {
                      JOptionPane.showMessageDialog(null, "Invalid month!\nPlease enter a valid month."); 
                  }
                  else {
                      dateMonth = mm; 
                      numCorrectFields++;
                   }  
              } catch (NumberFormatException e) {
                 JOptionPane.showMessageDialog(null, "Month is not a valid number!\nPlease enter a valid month.");
             }
         }
        
         //Check year
         if(jDateYear.getText().equalsIgnoreCase("yyyy") || jDateYear.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Year field is empty!\nPlease enter a year."); 
         }
         else {
              try { 
                 if(yyyy < 2021 || yyyy > 2026) {
                     JOptionPane.showMessageDialog(null, "Exams can only be created from 2021 to 2026. Please enter a valid year."); 
                 }
                 else {
                        dateYear = yyyy;
                        numCorrectFields++;
                 }  
              } catch (NumberFormatException e) {
                   JOptionPane.showMessageDialog(null, "Year is not a valid number!\nPlease enter valid year.");
               }
          }
        
         //Check if time is selected 
          if (jTimeComboBox.getSelectedItem() == "Make a Selection") {
              JOptionPane.showMessageDialog(null, "Time not selected!\nPlease select a time."); 
          } else {
              time = jTimeComboBox.getSelectedItem().toString();
              numCorrectFields++;
          }
        
          //Check location 
          if (jTextLocation.getText().equals("Room A123") || jTextLocation.getText().equals("Room A167") 
              || jTextLocation.getText().equals("Room B198") || jTextLocation.getText().equals("Room B067")) {
                location = jTextLocation.getText();
                numCorrectFields++;
          } else {
              JOptionPane.showMessageDialog(null, "Not a valid exam location!\n"
                      + "Please enter one of the following valid locations:\n"
                      + "Room A123, Room A167, Room B198 or Room B067.");
          }
           
          //Check examID  
          String regex = "^[E][1-9][0-9]{4}$";
          String input = jExamID.getText();
          valid = input.matches(regex);
          if(jExamID.getText().isEmpty()) {
              JOptionPane.showMessageDialog(null, "Exam ID has not been generated!\nPlease generate exam ID."); 
          } else if(!valid) {
              JOptionPane.showMessageDialog(null, "Invalid exam ID.\nExam ID must follow the format 'E'+ 5 numbers.");
          } else {
              examID = jExamID.getText();
              numCorrectFields++;
          }
          
         //Check if all fields are correct  
         if (numCorrectFields < NUM_FIELDS) {
             JOptionPane.showMessageDialog(null, "Exam could not be created.\nPlease try again.");   
         } else {
             ViewExams.AddRowToJTable(new Object[]{
             examID, date, selectedTime, location});
             JOptionPane.showMessageDialog(null, "Exam successfully created!"); 
         }
             
    }//GEN-LAST:event_jCreateExamButtonActionPerformed
        
    private void jGenerateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenerateIDActionPerformed
       java.util.Random r = new java.util.Random();
        int start = 10000; 
        int end = 99999; 
        int result = r.nextInt(end-start) + start; 
        String id = "E" + String.valueOf(result);
        jExamID.setText(id); 
    }//GEN-LAST:event_jGenerateIDActionPerformed

    private void jDateDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateDayActionPerformed

    private void jDateDayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateDayMouseClicked
        jDateDay.setText("");
    }//GEN-LAST:event_jDateDayMouseClicked

    private void jDateMonthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateMonthMouseClicked
        jDateMonth.setText("");
    }//GEN-LAST:event_jDateMonthMouseClicked

    private void jDateYearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateYearMouseClicked
        jDateYear.setText("");
    }//GEN-LAST:event_jDateYearMouseClicked

    private void jTextLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextLocationMouseClicked
        jTextLocation.setText("");
    }//GEN-LAST:event_jTextLocationMouseClicked

    private void jResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetButtonActionPerformed
        jDateDay.setText("dd");
        jDateMonth.setText("mm");
        jDateYear.setText("yyyy");
        jTextLocation.setText("Room A123");
        jExamID.setText("");
        jTimeComboBox.setSelectedItem("Make a Selection");
        jCourseComboBox.setSelectedItem("Make a Selection");
        
    }//GEN-LAST:event_jResetButtonActionPerformed

    private void jDateMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateMonthActionPerformed
       
    }//GEN-LAST:event_jDateMonthActionPerformed

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jCancelButtonActionPerformed

    private void jCourseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCourseComboBoxActionPerformed
        
    }//GEN-LAST:event_jCourseComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateExam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancelButton;
    private javax.swing.JComboBox<String> jCourseComboBox;
    private javax.swing.JButton jCreateExamButton;
    private javax.swing.JTextField jDateDay;
    private javax.swing.JLabel jDateLabel;
    private javax.swing.JTextField jDateMonth;
    private javax.swing.JTextField jDateYear;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JTextField jExamID;
    private javax.swing.JLabel jExamIDLabel;
    private javax.swing.JButton jGenerateID;
    private javax.swing.JLabel jHeaderLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLocationLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jResetButton;
    private javax.swing.JLabel jSelectCourseLabel;
    private javax.swing.JLabel jSelectTimeLabel;
    private javax.swing.JTextField jTextLocation;
    private javax.swing.JComboBox<String> jTimeComboBox;
    private javax.swing.JButton jUpdateButton;
    // End of variables declaration//GEN-END:variables
    private String course;
    private int dateDay;
    private int dateMonth;
    private int dateYear; 
    private String time; 
    private String location; 
    private String examID;
}
