/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CourseController;
import model.Course;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.JOptionPane;
import java.util.*;
/**
 *
 * @author jackie-sally
 */
public class CreateCourse extends javax.swing.JFrame {
    
    ArrayList<Course> courses; 
    /**
     * Creates new form CreateCourse
     */
    public CreateCourse() {
        initComponents();
        courses = new ArrayList<Course>();
        populateArrayList(); 
        
    }
    
    public void populateArrayList() {
        try{
           FileInputStream file = new FileInputStream("Courses.dat");
           ObjectInputStream inputFile = new ObjectInputStream(file);
           
           boolean endOfFile = false;
           
           while(!endOfFile){
               try {
                courses.add((Course)inputFile.readObject());
               }
               catch(EOFException e){
                endOfFile = true;    
               }
               catch(Exception f){
                JOptionPane.showMessageDialog(null, f.getMessage());    
               }
           }
           inputFile.close(); 
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage()); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextCourseName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextCredit = new javax.swing.JTextField();
        jCreateButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonGenerate = new javax.swing.JButton();
        jTextCourseCode = new javax.swing.JTextField();
        jDeleteButton = new javax.swing.JButton();
        jSaveButton = new javax.swing.JButton();
        jCancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel1.setText("Manage Course");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 48, -1, -1));

        jLabel2.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel2.setText("Course name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jTextCourseName.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jPanel1.add(jTextCourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 211, 35));

        jLabel3.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel3.setText("Credit");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 82, -1));

        jTextCredit.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jPanel1.add(jTextCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 92, 34));

        jCreateButton.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jCreateButton.setText("Create course");
        jCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(jCreateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 314, 124, -1));

        jLabel4.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel4.setText("Course code");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jButtonGenerate.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jButtonGenerate.setText("Generate");
        jButtonGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 174, 113, -1));

        jTextCourseCode.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jTextCourseCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCourseCodeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextCourseCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 92, 35));

        jDeleteButton.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        jDeleteButton.setText("Delete course");
        jPanel1.add(jDeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 314, -1, -1));

        jSaveButton.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jSaveButton.setText("Save update");
        jPanel1.add(jSaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 314, 124, -1));

        jCancelButton.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jCancelButton.setText("Cancel");
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(jCancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 378, 125, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateActionPerformed
    java.util.Random r = new java.util.Random();
    int start = 10000; 
    int end = 99999; 
    int result = r.nextInt(end-start) + start; 
    String code = "C" + String.valueOf(result);
    jTextCourseCode.setText(code); 
    }//GEN-LAST:event_jButtonGenerateActionPerformed

    private void jCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateButtonActionPerformed
        final int NUM_FIELDS = 3;
        int numCorrectFields = 0;
        boolean valid = true;
        boolean flag = true;  
        
   
        //Check course name
        if (jTextCourseName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Course has no name!\nPlease enter a course name."); 
        } else {
            courseName = jTextCourseName.getText();
            numCorrectFields++;
        }
        
        //Check course code 
        String regex = "^[C][1-9][0-9]{4}$";
        String input = jTextCourseCode.getText();
        valid = input.matches(regex);
        if (jTextCourseCode.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "A course must have a course code!\nPlease enter or generate a course code.");
        } else if(!valid) {
            JOptionPane.showMessageDialog(null, "Invalid course code\nCourse code must follow the format 'C'+ 5 numbers.");
        } else {
            courseCode = jTextCourseCode.getText();
            numCorrectFields++;
        }
     
        //Check credit 
        if (jTextCredit.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Course is missing credits!\nPlease enter course credit.");
        } else {
            try {
            courseCredit = Double.parseDouble(jTextCredit.getText());
            numCorrectFields++;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid course credit.\nPlease enter a number.");
            }
        }
        
        //Check if all fields are correct  
         if (numCorrectFields < NUM_FIELDS) {
             JOptionPane.showMessageDialog(null, "Course could not be created.\nPlease try again.");   
         } else {
            CourseMenu.AddRowToJTable(new Object[]{
                courseCode, courseName, courseCredit});
                JOptionPane.showMessageDialog(null, "Course successfully created!"); 
         }
    }//GEN-LAST:event_jCreateButtonActionPerformed

    private void jTextCourseCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCourseCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCourseCodeActionPerformed

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jCancelButtonActionPerformed
   
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerate;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JButton jCreateButton;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSaveButton;
    private javax.swing.JTextField jTextCourseCode;
    private javax.swing.JTextField jTextCourseName;
    private javax.swing.JTextField jTextCredit;
    // End of variables declaration//GEN-END:variables
   private CourseController coursecontroller; 
   private Course course; 
   private String courseName;
   private String courseCode; 
   private double courseCredit; 
   
}
