/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author jackie-sally
 */
public class RegisterResult extends javax.swing.JFrame {

    /**
     * Creates new form RegisterResult
     */
    public RegisterResult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jStudentLabel = new javax.swing.JLabel();
        jLastNameLabel = new javax.swing.JLabel();
        jFirstNameLabel = new javax.swing.JLabel();
        jExamLabel = new javax.swing.JLabel();
        jLastNameField = new javax.swing.JTextField();
        jFirstNameField = new javax.swing.JTextField();
        jStudentIDField = new javax.swing.JTextField();
        jExamIDField = new javax.swing.JTextField();
        jPointsField = new javax.swing.JTextField();
        jPointsLabel = new javax.swing.JLabel();
        jSaveButton = new javax.swing.JButton();
        jCancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(245, 245, 245));

        jLabel1.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel1.setText("Register exam results");

        jStudentLabel.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jStudentLabel.setText("Student ID:");

        jLastNameLabel.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLastNameLabel.setText("Last name:");

        jFirstNameLabel.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jFirstNameLabel.setText("First name:");

        jExamLabel.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jExamLabel.setText("Exam ID: ");

        jLastNameField.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N

        jFirstNameField.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N

        jStudentIDField.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N

        jExamIDField.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N

        jPointsField.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jPointsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPointsFieldActionPerformed(evt);
            }
        });

        jPointsLabel.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jPointsLabel.setText("Points:");

        jSaveButton.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jSaveButton.setText("Save");

        jCancelButton.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jCancelButton.setText("Cancel");
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jExamLabel)
                    .addComponent(jLastNameLabel)
                    .addComponent(jPointsLabel)
                    .addComponent(jFirstNameLabel)
                    .addComponent(jStudentLabel))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jExamIDField)
                    .addComponent(jStudentIDField)
                    .addComponent(jFirstNameField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPointsField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLastNameField))
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(150, 150, 150))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jExamLabel)
                    .addComponent(jExamIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStudentLabel)
                    .addComponent(jStudentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLastNameLabel)
                    .addComponent(jLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFirstNameLabel)
                    .addComponent(jFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPointsLabel)
                    .addComponent(jPointsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSaveButton)
                    .addComponent(jCancelButton))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPointsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPointsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPointsFieldActionPerformed

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jCancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancelButton;
    private javax.swing.JTextField jExamIDField;
    private javax.swing.JLabel jExamLabel;
    private javax.swing.JTextField jFirstNameField;
    private javax.swing.JLabel jFirstNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jLastNameField;
    private javax.swing.JLabel jLastNameLabel;
    private javax.swing.JTextField jPointsField;
    private javax.swing.JLabel jPointsLabel;
    private javax.swing.JButton jSaveButton;
    private javax.swing.JTextField jStudentIDField;
    private javax.swing.JLabel jStudentLabel;
    // End of variables declaration//GEN-END:variables
}
