/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author jackie-sally
 */
public class ViewExam extends javax.swing.JFrame {

    /**
     * Creates new form ViewExam
     */
    public ViewExam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSidePanel = new javax.swing.JPanel();
        jExamLabel1 = new javax.swing.JLabel();
        jRegisterPanel = new javax.swing.JPanel();
        jRegisterResultsButton = new javax.swing.JButton();
        jEditPanel = new javax.swing.JPanel();
        jEditResultsButton = new javax.swing.JButton();
        jExitPanel = new javax.swing.JPanel();
        jExitButton = new javax.swing.JButton();
        jStatsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMedianField = new javax.swing.JTextField();
        jPassingStudentsField = new javax.swing.JTextField();
        jAverageField = new javax.swing.JTextField();
        jExamLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTablePanel = new javax.swing.JPanel();
        jStudentScrollPane = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSearchField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(41, 57, 80));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSidePanel.setBackground(new java.awt.Color(0, 0, 0));
        jSidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jExamLabel1.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        jExamLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jExamLabel1.setText("Exam view");
        jSidePanel.add(jExamLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jRegisterPanel.setBackground(new java.awt.Color(0, 0, 0));

        jRegisterResultsButton.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jRegisterResultsButton.setForeground(new java.awt.Color(255, 255, 255));
        jRegisterResultsButton.setText("Register results");
        jRegisterResultsButton.setBorder(null);
        jRegisterResultsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jRegisterResultsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jRegisterResultsButtonMouseExited(evt);
            }
        });
        jRegisterResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterResultsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jRegisterPanelLayout = new javax.swing.GroupLayout(jRegisterPanel);
        jRegisterPanel.setLayout(jRegisterPanelLayout);
        jRegisterPanelLayout.setHorizontalGroup(
            jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRegisterResultsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jRegisterPanelLayout.setVerticalGroup(
            jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRegisterResultsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jSidePanel.add(jRegisterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 190, 60));

        jEditPanel.setBackground(new java.awt.Color(0, 0, 0));

        jEditResultsButton.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jEditResultsButton.setForeground(new java.awt.Color(255, 255, 255));
        jEditResultsButton.setText("Edit results");
        jEditResultsButton.setBorder(null);
        jEditResultsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jEditResultsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jEditResultsButtonMouseExited(evt);
            }
        });
        jEditResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditResultsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jEditPanelLayout = new javax.swing.GroupLayout(jEditPanel);
        jEditPanel.setLayout(jEditPanelLayout);
        jEditPanelLayout.setHorizontalGroup(
            jEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEditResultsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jEditPanelLayout.setVerticalGroup(
            jEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEditPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jEditResultsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSidePanel.add(jEditPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 190, 60));

        jExitPanel.setBackground(new java.awt.Color(0, 0, 0));

        jExitButton.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jExitButton.setForeground(new java.awt.Color(255, 255, 255));
        jExitButton.setText("Exit");
        jExitButton.setBorder(null);
        jExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jExitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jExitButtonMouseExited(evt);
            }
        });
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jExitPanelLayout = new javax.swing.GroupLayout(jExitPanel);
        jExitPanel.setLayout(jExitPanelLayout);
        jExitPanelLayout.setHorizontalGroup(
            jExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jExitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jExitPanelLayout.setVerticalGroup(
            jExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jSidePanel.add(jExitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 190, 60));

        getContentPane().add(jSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 627));

        jStatsPanel.setBackground(new java.awt.Color(23, 35, 51));
        jStatsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Average result in points ");
        jStatsPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 216, -1, -1));

        jLabel2.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Median result in points");
        jStatsPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel3.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Number of passing students ");
        jStatsPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));

        jMedianField.setBackground(new java.awt.Color(23, 35, 51));
        jMedianField.setFont(new java.awt.Font("Futura", 0, 36)); // NOI18N
        jMedianField.setForeground(new java.awt.Color(255, 255, 255));
        jMedianField.setText("85");
        jMedianField.setBorder(null);
        jMedianField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMedianFieldActionPerformed(evt);
            }
        });
        jStatsPanel.add(jMedianField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 142, 66));

        jPassingStudentsField.setBackground(new java.awt.Color(23, 35, 51));
        jPassingStudentsField.setFont(new java.awt.Font("Futura", 0, 36)); // NOI18N
        jPassingStudentsField.setForeground(new java.awt.Color(255, 255, 255));
        jPassingStudentsField.setText("100");
        jPassingStudentsField.setBorder(null);
        jPassingStudentsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassingStudentsFieldActionPerformed(evt);
            }
        });
        jStatsPanel.add(jPassingStudentsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 142, 66));

        jAverageField.setBackground(new java.awt.Color(23, 35, 51));
        jAverageField.setFont(new java.awt.Font("Futura", 0, 36)); // NOI18N
        jAverageField.setForeground(new java.awt.Color(255, 255, 255));
        jAverageField.setText("85");
        jAverageField.setBorder(null);
        jAverageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAverageFieldActionPerformed(evt);
            }
        });
        jStatsPanel.add(jAverageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 142, 66));

        jExamLabel.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jExamLabel.setForeground(new java.awt.Color(255, 255, 255));
        jExamLabel.setText("Statistics");
        jStatsPanel.add(jExamLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jStatsPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 220, 3));

        getContentPane().add(jStatsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 220, 627));

        jTablePanel.setBackground(new java.awt.Color(245, 245, 245));

        jTable1.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Last name", "First name", "Points", "Grade"
            }
        ));
        jStudentScrollPane.setViewportView(jTable1);

        jSearchField.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jSearchField.setText("Search...");
        jSearchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSearchFieldMouseClicked(evt);
            }
        });
        jSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTablePanelLayout = new javax.swing.GroupLayout(jTablePanel);
        jTablePanel.setLayout(jTablePanelLayout);
        jTablePanelLayout.setHorizontalGroup(
            jTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTablePanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jStudentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        jTablePanelLayout.setVerticalGroup(
            jTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTablePanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jStudentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getContentPane().add(jTablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setColor(JPanel p) {
        p.setBackground(new Color(18,20,22));
    }
    public void resetColor(JPanel p) {
        p.setBackground(new Color(0,0,0));
    }
    private void jSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchFieldActionPerformed

    private void jRegisterResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterResultsButtonActionPerformed
        new RegisterResult().setVisible(true);
    }//GEN-LAST:event_jRegisterResultsButtonActionPerformed

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void jMedianFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMedianFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMedianFieldActionPerformed

    private void jPassingStudentsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassingStudentsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassingStudentsFieldActionPerformed

    private void jAverageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAverageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAverageFieldActionPerformed

    private void jEditResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditResultsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEditResultsButtonActionPerformed

    private void jRegisterResultsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegisterResultsButtonMouseEntered
        setColor(jRegisterPanel);
    }//GEN-LAST:event_jRegisterResultsButtonMouseEntered

    private void jRegisterResultsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegisterResultsButtonMouseExited
        resetColor(jRegisterPanel);
    }//GEN-LAST:event_jRegisterResultsButtonMouseExited

    private void jEditResultsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEditResultsButtonMouseEntered
        setColor(jEditPanel);
    }//GEN-LAST:event_jEditResultsButtonMouseEntered

    private void jEditResultsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEditResultsButtonMouseExited
        resetColor(jEditPanel);
    }//GEN-LAST:event_jEditResultsButtonMouseExited

    private void jExitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitButtonMouseEntered
        setColor(jExitPanel);
    }//GEN-LAST:event_jExitButtonMouseEntered

    private void jExitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitButtonMouseExited
        resetColor(jExitPanel);
    }//GEN-LAST:event_jExitButtonMouseExited

    private void jSearchFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchFieldMouseClicked
        jSearchField.setText("");
    }//GEN-LAST:event_jSearchFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewExam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAverageField;
    private javax.swing.JPanel jEditPanel;
    private javax.swing.JButton jEditResultsButton;
    private javax.swing.JLabel jExamLabel;
    private javax.swing.JLabel jExamLabel1;
    private javax.swing.JButton jExitButton;
    private javax.swing.JPanel jExitPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jMedianField;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jPassingStudentsField;
    private javax.swing.JPanel jRegisterPanel;
    private javax.swing.JButton jRegisterResultsButton;
    private javax.swing.JTextField jSearchField;
    private javax.swing.JPanel jSidePanel;
    private javax.swing.JPanel jStatsPanel;
    private javax.swing.JScrollPane jStudentScrollPane;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jTablePanel;
    // End of variables declaration//GEN-END:variables
}
