/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author jackie-sally
 */
public class ViewResults extends javax.swing.JFrame {

    /**
     * Creates new form ViewExam
     */
    public ViewResults() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSidePanel = new javax.swing.JPanel();
        jExamLabel1 = new javax.swing.JLabel();
        jRegisterPanel = new javax.swing.JPanel();
        jRegisterResultsButton = new javax.swing.JButton();
        jExitPanel = new javax.swing.JPanel();
        jExitButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jStatsPanel = new javax.swing.JPanel();
        jAverageLabel = new javax.swing.JLabel();
        jMedianLabel = new javax.swing.JLabel();
        jNbrOfStudentsLabel = new javax.swing.JLabel();
        jMedianField = new javax.swing.JTextField();
        jPassingStudentsField = new javax.swing.JTextField();
        jAverageField = new javax.swing.JTextField();
        jExamLabel = new javax.swing.JLabel();
        jTablePanel = new javax.swing.JPanel();
        jStudentScrollPane = new javax.swing.JScrollPane();
        jResultsTable = new javax.swing.JTable();
        jSearchField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(41, 57, 80));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSidePanel.setBackground(new java.awt.Color(23, 35, 51));
        jSidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jExamLabel1.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        jExamLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jExamLabel1.setText("Results");
        jSidePanel.add(jExamLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jRegisterPanel.setBackground(new java.awt.Color(23, 35, 51));

        jRegisterResultsButton.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jRegisterResultsButton.setForeground(new java.awt.Color(255, 255, 255));
        jRegisterResultsButton.setText("Register results");
        jRegisterResultsButton.setBorder(null);
        jRegisterResultsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jRegisterResultsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jRegisterResultsButtonMouseExited(evt);
            }
        });
        jRegisterResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterResultsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jRegisterPanelLayout = new javax.swing.GroupLayout(jRegisterPanel);
        jRegisterPanel.setLayout(jRegisterPanelLayout);
        jRegisterPanelLayout.setHorizontalGroup(
            jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRegisterResultsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jRegisterPanelLayout.setVerticalGroup(
            jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRegisterResultsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jSidePanel.add(jRegisterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 200, 60));

        jExitPanel.setBackground(new java.awt.Color(23, 35, 51));

        jExitButton.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jExitButton.setForeground(new java.awt.Color(255, 255, 255));
        jExitButton.setText("Exit");
        jExitButton.setBorder(null);
        jExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jExitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jExitButtonMouseExited(evt);
            }
        });
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jExitPanelLayout = new javax.swing.GroupLayout(jExitPanel);
        jExitPanel.setLayout(jExitPanelLayout);
        jExitPanelLayout.setHorizontalGroup(
            jExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jExitPanelLayout.setVerticalGroup(
            jExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jSidePanel.add(jExitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 200, 60));

        jTextField1.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jTextField1.setText("Enter exam ID");
        jSidePanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 150, -1));

        jButton1.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jButton1.setText("View");
        jSidePanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 150, -1));

        jLabel4.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Or select exam below");
        jSidePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select course", "Item 2", "Item 3", "Item 4" }));
        jSidePanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 150, -1));

        jLabel6.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enter exam ID to view:");
        jSidePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jSidePanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 3));

        getContentPane().add(jSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 627));

        jStatsPanel.setBackground(new java.awt.Color(0, 0, 0));
        jStatsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jAverageLabel.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jAverageLabel.setForeground(new java.awt.Color(255, 255, 255));
        jAverageLabel.setText("Average result in points ");
        jStatsPanel.add(jAverageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jMedianLabel.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jMedianLabel.setForeground(new java.awt.Color(255, 255, 255));
        jMedianLabel.setText("Median result in points");
        jStatsPanel.add(jMedianLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jNbrOfStudentsLabel.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jNbrOfStudentsLabel.setForeground(new java.awt.Color(255, 255, 255));
        jNbrOfStudentsLabel.setText("Number of passing students ");
        jStatsPanel.add(jNbrOfStudentsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jMedianField.setBackground(new java.awt.Color(0, 0, 0));
        jMedianField.setFont(new java.awt.Font("Futura", 0, 36)); // NOI18N
        jMedianField.setForeground(new java.awt.Color(255, 255, 255));
        jMedianField.setText("85");
        jMedianField.setBorder(null);
        jMedianField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMedianFieldActionPerformed(evt);
            }
        });
        jStatsPanel.add(jMedianField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 142, 66));

        jPassingStudentsField.setBackground(new java.awt.Color(0, 0, 0));
        jPassingStudentsField.setFont(new java.awt.Font("Futura", 0, 36)); // NOI18N
        jPassingStudentsField.setForeground(new java.awt.Color(255, 255, 255));
        jPassingStudentsField.setText("100");
        jPassingStudentsField.setBorder(null);
        jPassingStudentsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassingStudentsFieldActionPerformed(evt);
            }
        });
        jStatsPanel.add(jPassingStudentsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 142, 66));

        jAverageField.setBackground(new java.awt.Color(0, 0, 0));
        jAverageField.setFont(new java.awt.Font("Futura", 0, 36)); // NOI18N
        jAverageField.setForeground(new java.awt.Color(255, 255, 255));
        jAverageField.setText("85");
        jAverageField.setBorder(null);
        jAverageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAverageFieldActionPerformed(evt);
            }
        });
        jStatsPanel.add(jAverageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 142, 66));

        jExamLabel.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jExamLabel.setForeground(new java.awt.Color(255, 255, 255));
        jExamLabel.setText("Exam Statistics");
        jStatsPanel.add(jExamLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        getContentPane().add(jStatsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 210, 627));

        jTablePanel.setBackground(new java.awt.Color(245, 245, 245));

        jResultsTable.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jResultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Last name", "First name", "Points", "Grade"
            }
        ));
        jStudentScrollPane.setViewportView(jResultsTable);

        jSearchField.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jSearchField.setText("Search...");
        jSearchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSearchFieldMouseClicked(evt);
            }
        });
        jSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTablePanelLayout = new javax.swing.GroupLayout(jTablePanel);
        jTablePanel.setLayout(jTablePanelLayout);
        jTablePanelLayout.setHorizontalGroup(
            jTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTablePanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jStudentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        jTablePanelLayout.setVerticalGroup(
            jTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTablePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jStudentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jTablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setColor(JPanel p) {
        p.setBackground(new Color(41,57,80));
    }
    public void resetColor(JPanel p) {
        p.setBackground(new Color(23,35,51));
    }
    private void jSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchFieldActionPerformed

    private void jRegisterResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterResultsButtonActionPerformed
        new RegisterResult().setVisible(true);
    }//GEN-LAST:event_jRegisterResultsButtonActionPerformed

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void jMedianFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMedianFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMedianFieldActionPerformed

    private void jPassingStudentsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassingStudentsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassingStudentsFieldActionPerformed

    private void jAverageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAverageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAverageFieldActionPerformed

    private void jRegisterResultsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegisterResultsButtonMouseEntered
        setColor(jRegisterPanel);
    }//GEN-LAST:event_jRegisterResultsButtonMouseEntered

    private void jRegisterResultsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegisterResultsButtonMouseExited
        resetColor(jRegisterPanel);
    }//GEN-LAST:event_jRegisterResultsButtonMouseExited

    private void jExitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitButtonMouseEntered
        setColor(jExitPanel);
    }//GEN-LAST:event_jExitButtonMouseEntered

    private void jExitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitButtonMouseExited
        resetColor(jExitPanel);
    }//GEN-LAST:event_jExitButtonMouseExited

    private void jSearchFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchFieldMouseClicked
        jSearchField.setText("");
    }//GEN-LAST:event_jSearchFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewResults().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAverageField;
    private javax.swing.JLabel jAverageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jExamLabel;
    private javax.swing.JLabel jExamLabel1;
    private javax.swing.JButton jExitButton;
    private javax.swing.JPanel jExitPanel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jMedianField;
    private javax.swing.JLabel jMedianLabel;
    private javax.swing.JLabel jNbrOfStudentsLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPassingStudentsField;
    private javax.swing.JPanel jRegisterPanel;
    private javax.swing.JButton jRegisterResultsButton;
    private javax.swing.JTable jResultsTable;
    private javax.swing.JTextField jSearchField;
    private javax.swing.JPanel jSidePanel;
    private javax.swing.JPanel jStatsPanel;
    private javax.swing.JScrollPane jStudentScrollPane;
    private javax.swing.JPanel jTablePanel;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
