/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author jackie-sally
 */
public class ViewCourse extends javax.swing.JFrame {

    /**
     * Creates new form ViewCourse
     */
    public ViewCourse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCourseLabel = new javax.swing.JLabel();
        jExamScrollPane = new javax.swing.JScrollPane();
        jExamTable = new javax.swing.JTable();
        jSearchField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jViewPanel = new javax.swing.JPanel();
        jViewExamButton = new javax.swing.JButton();
        jManagePanel = new javax.swing.JPanel();
        jEditExamButton = new javax.swing.JButton();
        jExitPanel = new javax.swing.JPanel();
        jExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(250, 250, 250));

        jCourseLabel.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        jCourseLabel.setText("Course view");

        jExamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exam ID", "Date", "Time", "Location"
            }
        ));
        jExamScrollPane.setViewportView(jExamTable);

        jSearchField.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jSearchField.setText("Search...");
        jSearchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSearchFieldMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(23, 35, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jViewPanel.setBackground(new java.awt.Color(23, 35, 51));

        jViewExamButton.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jViewExamButton.setForeground(new java.awt.Color(255, 255, 255));
        jViewExamButton.setText("View exam");
        jViewExamButton.setBorder(null);
        jViewExamButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jViewExamButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jViewExamButtonMouseExited(evt);
            }
        });
        jViewExamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViewExamButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jViewPanelLayout = new javax.swing.GroupLayout(jViewPanel);
        jViewPanel.setLayout(jViewPanelLayout);
        jViewPanelLayout.setHorizontalGroup(
            jViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jViewExamButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jViewPanelLayout.setVerticalGroup(
            jViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jViewPanelLayout.createSequentialGroup()
                .addComponent(jViewExamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel1.add(jViewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 210, 60));

        jManagePanel.setBackground(new java.awt.Color(23, 35, 51));

        jEditExamButton.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jEditExamButton.setForeground(new java.awt.Color(255, 255, 255));
        jEditExamButton.setText("Manage exams");
        jEditExamButton.setBorder(null);
        jEditExamButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jEditExamButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jEditExamButtonMouseExited(evt);
            }
        });
        jEditExamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditExamButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jManagePanelLayout = new javax.swing.GroupLayout(jManagePanel);
        jManagePanel.setLayout(jManagePanelLayout);
        jManagePanelLayout.setHorizontalGroup(
            jManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEditExamButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jManagePanelLayout.setVerticalGroup(
            jManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEditExamButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jManagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 210, 60));

        jExitPanel.setBackground(new java.awt.Color(23, 35, 51));

        jExitButton.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jExitButton.setForeground(new java.awt.Color(255, 255, 255));
        jExitButton.setText("Exit");
        jExitButton.setBorder(null);
        jExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jExitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jExitButtonMouseExited(evt);
            }
        });
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jExitPanelLayout = new javax.swing.GroupLayout(jExitPanel);
        jExitPanel.setLayout(jExitPanelLayout);
        jExitPanelLayout.setHorizontalGroup(
            jExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jExitPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jExitPanelLayout.setVerticalGroup(
            jExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jExitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jExitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 210, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCourseLabel)
                            .addGap(492, 492, 492)))
                    .addComponent(jExamScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jCourseLabel)
                .addGap(39, 39, 39)
                .addComponent(jSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jExamScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
     public void setColor(JPanel p) {
        p.setBackground(new Color(41,57,80));
    }
    public void resetColor(JPanel p) {
        p.setBackground(new Color(23,35,51));
    }
    private void jViewExamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewExamButtonActionPerformed
        new ViewExam().setVisible(true);
    }//GEN-LAST:event_jViewExamButtonActionPerformed

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void jViewExamButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jViewExamButtonMouseEntered
        setColor(jViewPanel);
    }//GEN-LAST:event_jViewExamButtonMouseEntered

    private void jViewExamButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jViewExamButtonMouseExited
        resetColor(jViewPanel);
    }//GEN-LAST:event_jViewExamButtonMouseExited

    private void jExitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitButtonMouseEntered
        setColor(jExitPanel);
    }//GEN-LAST:event_jExitButtonMouseEntered

    private void jExitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitButtonMouseExited
        resetColor(jExitPanel);
    }//GEN-LAST:event_jExitButtonMouseExited

    private void jEditExamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditExamButtonActionPerformed
        new CreateExam().setVisible(true);
    }//GEN-LAST:event_jEditExamButtonActionPerformed

    private void jEditExamButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEditExamButtonMouseExited
        resetColor(jManagePanel);
    }//GEN-LAST:event_jEditExamButtonMouseExited

    private void jEditExamButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEditExamButtonMouseEntered
        setColor(jManagePanel);
    }//GEN-LAST:event_jEditExamButtonMouseEntered

    private void jSearchFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchFieldMouseClicked
        jSearchField.setText("");
    }//GEN-LAST:event_jSearchFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCourseLabel;
    private javax.swing.JButton jEditExamButton;
    private javax.swing.JScrollPane jExamScrollPane;
    private javax.swing.JTable jExamTable;
    private javax.swing.JButton jExitButton;
    private javax.swing.JPanel jExitPanel;
    private javax.swing.JPanel jManagePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jSearchField;
    private javax.swing.JButton jViewExamButton;
    private javax.swing.JPanel jViewPanel;
    // End of variables declaration//GEN-END:variables
}
