/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author jackie-sally
 */
public class ViewExams_1 extends javax.swing.JFrame {
    
    DefaultTableModel dm;
    /**
     * Creates new form ViewCourse
     */
    public ViewExams_1() {
        initComponents();
    }
    //Filter data
    private void filter(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dm);
        jExamTable.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jExamScrollPane = new javax.swing.JScrollPane();
        jExamTable = new javax.swing.JTable();
        jSearchField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jAddPanel = new javax.swing.JPanel();
        jAddButton = new javax.swing.JButton();
        jExamLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSavePanel = new javax.swing.JPanel();
        jSaveButton = new javax.swing.JButton();
        jDeletePanel = new javax.swing.JPanel();
        jDeleteButton = new javax.swing.JButton();
        jResetPanel = new javax.swing.JPanel();
        jResetButton = new javax.swing.JButton();
        jExitPanel = new javax.swing.JPanel();
        jExitButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCourseLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(250, 250, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jExamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exam ID", "Date", "Time", "Location"
            }
        ));
        jExamScrollPane.setViewportView(jExamTable);

        getContentPane().add(jExamScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 133, 580, 460));

        jSearchField.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jSearchField.setText("Search...");
        jSearchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSearchFieldMouseClicked(evt);
            }
        });
        getContentPane().add(jSearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 186, -1));

        jPanel1.setBackground(new java.awt.Color(23, 35, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jAddPanel.setBackground(new java.awt.Color(23, 35, 51));

        jAddButton.setFont(new java.awt.Font("Futura", 0, 13)); // NOI18N
        jAddButton.setForeground(new java.awt.Color(255, 255, 255));
        jAddButton.setText("Add exam");
        jAddButton.setBorder(null);
        jAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jAddButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jAddButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jAddPanelLayout = new javax.swing.GroupLayout(jAddPanel);
        jAddPanel.setLayout(jAddPanelLayout);
        jAddPanelLayout.setHorizontalGroup(
            jAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        jAddPanelLayout.setVerticalGroup(
            jAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jAddPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 320, 30));

        jExamLabel.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        jExamLabel.setForeground(new java.awt.Color(255, 255, 255));
        jExamLabel.setText("Exams");
        jPanel1.add(jExamLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 320, 3));

        jLabel1.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Exam ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 180, -1));

        jLabel2.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select course:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 112, -1, -1));

        jLabel3.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Select time:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Location:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jTextField2.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jTextField2.setText("yyyy");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 50, -1));

        jTextField4.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jTextField4.setText("dd");
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 40, -1));

        jTextField5.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jTextField5.setText("mm");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 40, -1));

        jLabel6.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("/");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("/");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 226, 180, -1));

        jTextField3.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jTextField3.setText("Enter room number");
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 285, 180, -1));

        jTextField6.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 81, -1));

        jButton2.setFont(new java.awt.Font("Futura", 0, 13)); // NOI18N
        jButton2.setText("Generate");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("/");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        jSavePanel.setBackground(new java.awt.Color(23, 35, 51));

        jSaveButton.setFont(new java.awt.Font("Futura", 0, 13)); // NOI18N
        jSaveButton.setForeground(new java.awt.Color(255, 255, 255));
        jSaveButton.setText("Save");
        jSaveButton.setBorder(null);
        jSaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jSaveButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jSaveButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jSavePanelLayout = new javax.swing.GroupLayout(jSavePanel);
        jSavePanel.setLayout(jSavePanelLayout);
        jSavePanelLayout.setHorizontalGroup(
            jSavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        jSavePanelLayout.setVerticalGroup(
            jSavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSaveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jSavePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 320, 30));

        jDeletePanel.setBackground(new java.awt.Color(23, 35, 51));

        jDeleteButton.setFont(new java.awt.Font("Futura", 0, 13)); // NOI18N
        jDeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        jDeleteButton.setText("Delete");
        jDeleteButton.setBorder(null);
        jDeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jDeleteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jDeleteButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jDeletePanelLayout = new javax.swing.GroupLayout(jDeletePanel);
        jDeletePanel.setLayout(jDeletePanelLayout);
        jDeletePanelLayout.setHorizontalGroup(
            jDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        jDeletePanelLayout.setVerticalGroup(
            jDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDeleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jDeletePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 320, 30));

        jResetPanel.setBackground(new java.awt.Color(23, 35, 51));

        jResetButton.setFont(new java.awt.Font("Futura", 0, 13)); // NOI18N
        jResetButton.setForeground(new java.awt.Color(255, 255, 255));
        jResetButton.setText("Reset");
        jResetButton.setBorder(null);
        jResetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jResetButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jResetButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jResetPanelLayout = new javax.swing.GroupLayout(jResetPanel);
        jResetPanel.setLayout(jResetPanelLayout);
        jResetPanelLayout.setHorizontalGroup(
            jResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jResetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        jResetPanelLayout.setVerticalGroup(
            jResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jResetButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jResetPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 320, 30));

        jExitPanel.setBackground(new java.awt.Color(23, 35, 51));

        jExitButton.setFont(new java.awt.Font("Futura", 0, 13)); // NOI18N
        jExitButton.setForeground(new java.awt.Color(255, 255, 255));
        jExitButton.setText("Exit");
        jExitButton.setBorder(null);
        jExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jExitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jExitButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jExitPanelLayout = new javax.swing.GroupLayout(jExitPanel);
        jExitPanel.setLayout(jExitPanelLayout);
        jExitPanelLayout.setHorizontalGroup(
            jExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        jExitPanelLayout.setVerticalGroup(
            jExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jExitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 320, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 617));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jCourseLabel.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jCourseLabel.setForeground(new java.awt.Color(255, 255, 255));
        jCourseLabel.setText("View course:");

        jTextField1.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jTextField1.setText("Type in course code");

        jButton1.setFont(new java.awt.Font("Futura", 0, 13)); // NOI18N
        jButton1.setText("View");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jCourseLabel)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(224, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCourseLabel)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 0, 640, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
     public void setColor(JPanel p) {
        p.setBackground(new Color(41,57,80));
    }
    public void resetColor(JPanel p) {
        p.setBackground(new Color(23,35,51));
    }
    public static void AddRowToJTable(Object [] dataRow) {
        DefaultTableModel model = (DefaultTableModel)jExamTable.getModel();
        model.addRow(dataRow);
    }
    private void jSearchFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchFieldMouseClicked
        jSearchField.setText("");
    }//GEN-LAST:event_jSearchFieldMouseClicked

    private void jAddButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddButtonMouseEntered
        setColor(jAddPanel);
    }//GEN-LAST:event_jAddButtonMouseEntered

    private void jAddButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddButtonMouseExited
        resetColor(jAddPanel);
    }//GEN-LAST:event_jAddButtonMouseExited

    private void jSaveButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSaveButtonMouseEntered
        setColor(jSavePanel);
    }//GEN-LAST:event_jSaveButtonMouseEntered

    private void jSaveButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSaveButtonMouseExited
        resetColor(jSavePanel);
    }//GEN-LAST:event_jSaveButtonMouseExited

    private void jDeleteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDeleteButtonMouseEntered
        setColor(jDeletePanel);
    }//GEN-LAST:event_jDeleteButtonMouseEntered

    private void jDeleteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDeleteButtonMouseExited
        resetColor(jDeletePanel);
    }//GEN-LAST:event_jDeleteButtonMouseExited

    private void jResetButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jResetButtonMouseEntered
        setColor(jResetPanel);
    }//GEN-LAST:event_jResetButtonMouseEntered

    private void jResetButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jResetButtonMouseExited
        resetColor(jResetPanel);
    }//GEN-LAST:event_jResetButtonMouseExited

    private void jExitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitButtonMouseEntered
        setColor(jExitPanel);
    }//GEN-LAST:event_jExitButtonMouseEntered

    private void jExitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitButtonMouseExited
        resetColor(jExitPanel);
    }//GEN-LAST:event_jExitButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewExams_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddButton;
    private javax.swing.JPanel jAddPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jCourseLabel;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JPanel jDeletePanel;
    private javax.swing.JLabel jExamLabel;
    private javax.swing.JScrollPane jExamScrollPane;
    private static javax.swing.JTable jExamTable;
    private javax.swing.JButton jExitButton;
    private javax.swing.JPanel jExitPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jResetButton;
    private javax.swing.JPanel jResetPanel;
    private javax.swing.JButton jSaveButton;
    private javax.swing.JPanel jSavePanel;
    private javax.swing.JTextField jSearchField;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
